#ifndef CERT_H

#define CERT_H

const char * rootCACertificate = \
  "-----BEGIN CERTIFICATE-----\n"
"MIIDjjCCAnagAwIBAgIJQgAAAAdhirdVMA0GCSqGSIb3DQEBCwUAMFQxGTAXBgNV\n"
"BAoMEEFPIEthc3BlcnNreSBMYWIxNzA1BgNVBAMMLkthc3BlcnNreSBBbnRpLVZp\n"
"cnVzIFBlcnNvbmFsIFJvb3QgQ2VydGlmaWNhdGUwHhcNMjEwNTExMTgwMDUzWhcN\n"
"MjIwNTEwMTgwMDUzWjBmMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5p\n"
"YTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEVMBMGA1UEChMMR2l0SHViLCBJbmMu\n"
"MRMwEQYDVQQDEwpnaXRodWIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\n"
"CgKCAQEAtxXNahXrV/ZXTm8XZGrAyHDnwPvQgHDYCbwSPGDmPbCx8B0e+CSGFRyU\n"
"AeBZJdVIzPizGJm2OC4TQt8dG8yMhgSmfLi3iPzxpTbEd5BXOfEum/cVF4s1qZMd\n"
"RJJY52kpzxMRji/Twy6GNRjQiU18q51Ux2PsWG9QMbIvkIVsQvfvgSRDsgn9d5Wt\n"
"Ar57HE6NM85DdUbm/JHgjEVfWS4OwO8q6Z07VuNdlyriS2IkTducTnFzfHVN0vT0\n"
"8jgblLk5BMLUlIYmBAWqoChZYGX6khhsySCHZfl6nKe+yx/cmkZIBbkdVA+y+OD6\n"
"WLuK4tQymSjT2F9oNKBmG+Bf5IeLbQIDAQABo1EwTzATBgNVHSUEDDAKBggrBgEF\n"
"BQcDATALBgNVHQ8EBAMCBaAwKwYDVR0RBCQwIocEFMkcl4IKZ2l0aHViLmNvbYIO\n"
"d3d3LmdpdGh1Yi5jb20wDQYJKoZIhvcNAQELBQADggEBAHS0BcISr8IMFo2RcDTT\n"
"Rrt3phozn8bpIAAQUMlvlqx1H7xIGajKIpPtplNhNVx6dp3x6dWyxE7GN/qDshhT\n"
"/PyDQZ4Da3uejx5ns9aw7tb5T36CocfhofsVbYIqSbb/81rhJoyKB4fFeZWAYtjQ\n"
"fdHYIF3aYkE8qUEf+M3juodQOTKrF/kE0YbvD3N8x4U0f6QJvus4qbmn9ADRUaF+\n"
"wxgyDpIkdU5OhpFy2S8paepXnHf1r0pQx59bgYYJ6QraMrV1hTJo+RAPAdAleGR5\n"
"lC/taJrZY8Qmh7avgbnXi4bQf12yQxq5HrHUJ/GnEDvj1EM6sNFCHoVC6Apr/2lr\n"
"uFQ=\n"
"-----END CERTIFICATE-----\n";

#endif
